config/routes.rb
Rails.application.routes.draw do
  resources :hamburgers
  get 'users/sign_up' , to: 'users#new'
  post 'users', to: 'users#create'
  get 'users/sign_in', to: 'sessions#new'
  resources :sessions ,only:[:create,:destroy]
  root 'hamburgers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hamburger.rb
class Hamburger < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name , presence: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :password,presence: true
    
    has_many :hamburgers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def authenticate_user!
        redirect_to users_sign_in_path unless
        helpers.logged?    
        
    end
end

app/controllers/hamburgers_controller.rb
class HamburgersController < ApplicationController
  before_action :set_hamburger, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except:[:index]

  # GET /hamburgers
  # GET /hamburgers.json
  def index
    @hamburgers = Hamburger.all
  end

  # GET /hamburgers/1
  # GET /hamburgers/1.json
  def show
  end

  # GET /hamburgers/new
  def new
    @hamburger = Hamburger.new
  end

  # GET /hamburgers/1/edit
  def edit
  end

  # POST /hamburgers
  # POST /hamburgers.json
  def create
    @hamburger = Hamburger.new(hamburger_params)
    @hamburger.user = helpers.current_user
    respond_to do |format|
      if @hamburger.save
        format.html { redirect_to @hamburger, notice: 'Hamburger was successfully created.' }
        format.json { render :show, status: :created, location: @hamburger }
      else
        format.html { render :new }
        format.json { render json: @hamburger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hamburgers/1
  # PATCH/PUT /hamburgers/1.json
  def update
    respond_to do |format|
      if @hamburger.update(hamburger_params)
        format.html { redirect_to @hamburger, notice: 'Hamburger was successfully updated.' }
        format.json { render :show, status: :ok, location: @hamburger }
      else
        format.html { render :edit }
        format.json { render json: @hamburger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hamburgers/1
  # DELETE /hamburgers/1.json
  def destroy
    @hamburger.destroy
    respond_to do |format|
      format.html { redirect_to hamburgers_url, notice: 'Hamburger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hamburger
      @hamburger = Hamburger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hamburger_params
      params.require(:hamburger).permit(:name, :description, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.find_by(email: params[:user][:email],
    password: params[:user][:password])
    if @user.present?
    session[:user_id] = @user.id
    redirect_to root_path, notice: 'Has ingresado'
    else
    redirect_to root_path, alert: 'Tus credenciales no son
    válidas'
    end
  end

  
  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
      #  before_action :user_params, only: [:show, :edit, :update, :destroy]
    
        def new
          @user = User.new
        end
      
        # GET /hamburgers/1/edit
        def edit

        end
      
         def create
        @user= User.new(user_params)
          if @user.save
            session[:user_id] =@user.id
            redirect_to root_path
          else
           render :new
          end
        end
      
    
      private
        # Use callbacks to share common setup or constraints between actions.
        def user_params
        
          params.require(:user).permit(:name, :email,:password)
        end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hamburgers_helper.rb
module HamburgersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user
        User.find(session[:user_id])
    end
    def logged?
        session[:user_id].present? ? true : false
    end
end

app/views/hamburgers/_form.html.erb
<%= form_with(model: hamburger, local: true) do |form| %>
  <% if hamburger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hamburger.errors.count, "error") %> prohibited this hamburger from being saved:</h2>

      <ul>
      <% hamburger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hamburgers/edit.html.erb
<h1>Editing Hamburger</h1>

<%= render 'form', hamburger: @hamburger %>

<%= link_to 'Show', @hamburger %> |
<%= link_to 'Back', hamburgers_path %>

app/views/hamburgers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hamburgers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Creador</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hamburgers.each do |hamburger| %>
      <tr>
        <td><%= hamburger.name %></td>
        <td><%= hamburger.description %></td>
        <td><%= hamburger.user.name %></td>
        <td><%= hamburger.price %></td>
        <td><%= link_to 'Show', hamburger %></td>
        <td><%= link_to 'Edit', edit_hamburger_path(hamburger) %></td>
        <td><%= link_to 'Destroy', hamburger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hamburger', new_hamburger_path %>

app/views/hamburgers/new.html.erb
<h1>New Hamburger</h1>

<%= render 'form', hamburger: @hamburger %>

<%= link_to 'Back', hamburgers_path %>

app/views/hamburgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hamburger.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hamburger.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @hamburger.price %>
</p>

<%= link_to 'Edit', edit_hamburger_path(@hamburger) %> |
<%= link_to 'Back', hamburgers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManualAuthentication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home" ,hamburgers_path ,class:"nav-link"%>
      </li>
      <li class="nav-item">
       <%= link_to "Sing_up" ,users_sign_up_path ,class:"nav-link"%>
      </li>
    </ul>
    <ul>

    </ul>
  </div>
</nav>
<div class="container">

  <% if logged?%>

      Bienvenido <%=current_user.email %>
      <%= link_to "salir", session_path(current_user), method: :delete %>
    <% end %>
    <%=alert%>
    <%= yield %>
</div>    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with(model: @user, local: true) do |f| %>
 <% if @user.errors.any? %>
 <div class="error_messages">
 <h2>Form is invalid</h2>
 <ul>
 <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <div class="field">
 <%= f.label :name %><br />
 <%= f.text_field :name %>
 </div>
 <div class="field">
 <%= f.label :email %><br />
 <%= f.text_field :email %>
 </div>
 <div class="field">
 <%= f.label :password %><br />
 <%= f.password_field :password %>
 </div>
 <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>